name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4

      # - name: run tests
      #   run: composer run-script test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "7.1"

      - name: checkout code
        uses: actions/checkout@v2.3.4

      # - name: Validate composer.json and composer.lock
      #   run: |
      #     composer self-update --2.2
      #     composer validate --strict

      # - name: Cache Composer packages
      #   id: composer-cache
      #   uses: actions/cache@v3
      #   with:
      #     path: vendor
      #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer self-update --2.2
          composer install --prefer-dist --no-progress

      - name: ssh and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_STAGING }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          script: |
            cd /var/www/staging
            git pull origin staging
            composer install
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
